# Generated by Django 3.1.6 on 2021-03-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('no_documento', models.DecimalField(db_column='document_user', decimal_places=0, max_digits=13, null=True)),
                ('nombre', models.CharField(db_column='f_name', max_length=50)),
                ('apellido', models.CharField(db_column='l_name', max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('no_celular', models.DecimalField(db_column='cell_number', decimal_places=0, max_digits=10, null=True)),
                ('tel_fijo', models.DecimalField(blank=True, db_column='phone', decimal_places=0, max_digits=7, null=True)),
                ('direccion', models.CharField(db_column='address', max_length=50, null=True)),
                ('barrio', models.CharField(blank=True, db_column='neighborhood', max_length=50, null=True)),
                ('referencia_vivienda', models.CharField(blank=True, db_column='home_reference', max_length=50, null=True)),
                ('fecha_cumpleaños', models.DateField(blank=True, db_column='dob', null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('token_key', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True, db_column='register_date', null=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='cant_carpas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(db_column='cant', default=1)),
            ],
        ),
        migrations.CreateModel(
            name='carpas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('no_personas', models.DecimalField(decimal_places=0, max_digits=2)),
                ('no_carpas', models.DecimalField(decimal_places=0, default=1, max_digits=2)),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('url_img', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'carpa',
                'verbose_name_plural': 'carpas',
                'db_table': 'carpas',
            },
        ),
        migrations.CreateModel(
            name='contact_request',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='fname', max_length=60, null=True)),
                ('no_celular', models.DecimalField(blank=True, db_column='cell_phone', decimal_places=0, max_digits=10, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True)),
                ('mensaje', models.CharField(blank=True, db_column='message', max_length=300, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now=True, db_column='regis_date', null=True)),
                ('atendido', models.BooleanField(db_column='check_soli', default=False)),
            ],
            options={
                'verbose_name': 'solicitud de contacto',
                'verbose_name_plural': 'solicitudes de contacto',
                'db_table': 'contact_request',
            },
        ),
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('no_personas', models.DecimalField(decimal_places=0, default=2, max_digits=2)),
                ('nombre', models.CharField(max_length=30)),
                ('celular', models.DecimalField(decimal_places=0, default=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('no_documento', models.DecimalField(decimal_places=0, max_digits=13)),
            ],
            options={
                'verbose_name': 'reservacion',
                'verbose_name_plural': 'reservaciones',
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(db_column='name_ser', max_length=50)),
                ('oferta_servicio', models.CharField(db_column='service_offer', max_length=50)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='state_user',
            fields=[
                ('id_state_usr', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, db_column='name_st', max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='description', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'estado del usuario',
                'verbose_name_plural': 'estados de los usuarios',
                'db_table': 'state_user',
            },
        ),
        migrations.CreateModel(
            name='type_user',
            fields=[
                ('id_ty_us', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(db_column='type_name', max_length=50)),
            ],
            options={
                'verbose_name': 'tipo de usuario',
                'verbose_name_plural': 'tipos de usuarios',
                'db_table': 'type_user',
            },
        ),
        migrations.AddConstraint(
            model_name='reservas',
            constraint=models.UniqueConstraint(fields=('carpas', 'fecha_llegada'), name='reserva_carpa_uno'),
        ),
        migrations.AddConstraint(
            model_name='reservas',
            constraint=models.UniqueConstraint(fields=('carpas', 'fecha_salida'), name='reserva_carpa_dos'),
        ),
        migrations.AddField(
            model_name='cant_carpas',
            name='carpa',
            field=models.ForeignKey(db_column='carp', on_delete=django.db.models.deletion.DO_NOTHING, to='camping.carpas'),
        ),
        migrations.AddField(
            model_name='cant_carpas',
            name='reserva',
            field=models.ForeignKey(db_column='reser', on_delete=django.db.models.deletion.DO_NOTHING, to='camping.reservas'),
        ),
        migrations.AddField(
            model_name='users',
            name='estado',
            field=models.ForeignKey(db_column='state_usr', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='camping.state_user'),
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='users',
            name='tipo_usuario',
            field=models.ForeignKey(db_column='type_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='camping.type_user'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
