# Generated by Django 3.1.6 on 2021-03-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'estado de la reserva',
                'verbose_name_plural': 'estados de reserva',
                'db_table': 'states_reser',
            },
        ),
    ]
