# Generated by Django 3.1.6 on 2021-02-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tipo_usuario',
            field=models.ForeignKey(db_column='type_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='camping.type_user'),
        ),
    ]
