# Generated by Django 3.1.6 on 2021-02-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_auto_20210225_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_request',
            name='mensaje',
            field=models.CharField(blank=True, db_column='message', max_length=300, null=True),
        ),
    ]
