# Generated by Django 3.1.6 on 2021-03-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0002_estado_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='estado',
            field=models.ForeignKey(db_column='state', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='camping.estado_reservas'),
        ),
    ]
