# Generated by Django 3.1.6 on 2021-03-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0003_reservas_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cant_carpas',
            options={'verbose_name': 'carpas por reserva', 'verbose_name_plural': 'carpas por reserva'},
        ),
        migrations.AlterModelTable(
            name='cant_carpas',
            table='cant_carpa',
        ),
    ]
